import GlobalState from "../context/index";
import "./globals.css";
import { Inter } from "next/font/google";
import NextAuthProvider from "../auth-provider/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="./favicon.ico" /> 
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <GlobalState> 
            {children}
            </GlobalState>
        </NextAuthProvider>
      </body>
    </html>
  );
}